version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - fxProcessorDB
  fxProcessorDB:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: fxprocessing
      MYSQL_USER: rdongol
      MYSQL_PASSWORD: rawbean
      MYSQL_ROOT_PASSWORD: rawbean